### ISSUE TITLE
Tables not working with designer's table

### ISSUE THREAD

**Issue by Remyrios** [codetaylor/artisan-worktables#108] opened 2018-04-10 17:59 UTC
#### Issue Description

Tables won't work if you connect designer's table to them. After you break designer's table the main table is still unusable until you place other table in the place of the broken designer's table.

#### What Happens

Designer's table breaks interaction with tables attached to it.

#### What You Expect to Happen

Other tables should work fine with additional content added from designer's table.

#### Script

No scripts involved

#### Crash Log

No crash log involved

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.2.2654
* CraftTweaker: 4.1.6
* Artisan Worktables: 1.19.0-SNAPSHOT.2
* Athenaeum: 1.14.0

**Comment by codetaylor** [comment] 2018-04-10 18:44
I can't reproduce this.

Please elaborate on:

> Tables won't work if you connect designer's table to them.

Please provide detailed steps to reproduce this issue, thanks.

**Comment by codetaylor** [comment] 2018-04-10 18:51
https://streamable.com/j4yp7

**Comment by Remyrios** [comment] 2018-04-10 19:26
https://streamable.com/ojvhc Sorry for the lag just my pc isn't the best

**Comment by codetaylor** [comment] 2018-04-10 20:16
From the video, it looks like these are the steps:

1. Place Blacksmith's Table (BT)
2. Add bucket of water to BT
3. Verify 1000mb of water in BT
4. Place Designer's Table (DT) adjacent to BT
5. Attempt to add bucket of water to BT
6. Observe water is not added
7. Attempt to open the BT gui
8. Observe gui does not open

I followed the same steps that I observed in your video and I still can't reproduce the issue.

Can you reproduce the issue using the same versions, with no other mods present? It may be a mod conflict issue.

I was using Forge 2635 and I'm updating to the version you listed, 2654. I'll see if I can reproduce this with that version.

**Comment by codetaylor** [comment] 2018-04-10 20:29
I've updated to Forge 2654 and no luck reproducing the issue.

https://streamable.com/bkwv3

At this point, my best guess is that the issue is a mod interaction issue.

**Comment by Remyrios** [comment] 2018-04-10 20:32
That water bucket was there by mistake :P I will check without any other mods

**Comment by codetaylor** [comment] 2018-04-10 20:37
Ok, thank you. Please let me know what you discover. :)

**Comment by Remyrios** [comment] 2018-04-10 20:42
It doesn't work with just Artisan Wokrtables, Athenaeum and CraftTweaker

**Comment by codetaylor** [comment] 2018-04-10 20:43
Is there anything in your log file related to this mod?

**Comment by codetaylor** [comment] 2018-04-10 20:45
And, to be clear, by "doesn't work", you mean that you are still experiencing the problem?

**Comment by Remyrios** [comment] 2018-04-10 20:45
Yeah, I found something related to designer's table, here is the log: https://hastebin.com/usiselemic.md

**Comment by Remyrios** [comment] 2018-04-10 20:47
Yes it's the same issue

**Comment by Remyrios** [comment] 2018-04-10 20:48
Also if that helps my java version is 1.8.0_131

**Comment by codetaylor** [comment] 2018-04-10 20:48
Ok, great! Something I can work with! :)

This is in single player, correct?

**Comment by codetaylor** [comment] 2018-04-10 20:50
This is a weird one, because `AbstractMethodError` is:

> Thrown when an application tries to call an abstract method. Normally, this error is caught by the compiler; this error can only occur at run time if the definition of some class has incompatibly changed since the currently executing method was last compiled.

This could indicate that there is something wrong with the version on Curse.

**Comment by Remyrios** [comment] 2018-04-10 20:52
It also happened on snapshot 1 too - another info

**Comment by Remyrios** [comment] 2018-04-10 20:53
And yes it is SP

**Comment by codetaylor** [comment] 2018-04-10 22:01
I was able to reproduce this issue by doing the following:

1. Setup new instance in Twitch launcher using Forge 2654
2. Download Artisan Worktables 1.19.0-SNAPSHOT.2
3. Download Athenaeum 1.14.0
4. Follow the steps in https://github.com/codetaylor/artisan-worktables/issues/108#issuecomment-380232543

This instance runs Java 1.8.0_25.

The mod is built against Java 1.8.0_144.

Next, I'm going to attempt the same test with this Twitch instance, but point it to use my installed JRE version 1.8.0_144.

**Comment by codetaylor** [comment] 2018-04-10 22:03
The issue still occurs with 1.8.0_144 running it with the Twitch instance and the publicly available jars.

**Comment by codetaylor** [comment] 2018-04-10 22:16
Ok, I finally understand why this is happening.

I have an interface `ITileEntityDesigner` which is implemented by all my designer table tile entities. These TE's also extend the class `TileEntity`, obviously. The method `boolean ITileEntityDesigner#isInvalid()` is then satisfied by the super class method `boolean TileEntity#isInvalid()`.

The method that satisfies the abstract requirement of the interface is, however, re-obfuscated at compile time because the method is part of the obfuscated MC codebase. This means that when the method is called at runtime, there is no longer an implementation of the method to back the abstract signature, and the `AbstractMethodError` is thrown.

It makes sense now!

Thanks for bringing this to my attention. It should be fixed up in the next alpha snapshot.

**Comment by codetaylor** [comment] 2018-04-11 16:10
Fixed in 1.12.2-1.19.0-SNAPSHOT.3

**Closed as completed by codetaylor** 2018-04-11 16:10 UTC
Labels: bug, reproduced, complete
