### ISSUE TITLE
Crash while taking out or putting in items.

### ISSUE THREAD

**Issue by Remyrios** [codetaylor/artisan-worktables#48] opened 2018-02-03 21:22 UTC
**Artisan Worktables Version:** 1.11.20
**Athenaeum Version:** 1.6.3
**CraftTweaker Version:** 4.1.2
**Forge Version:** 14.23.1.2601
**Crashlog:** https://hastebin.com/awanacocik.sql
**Script:** https://hastebin.com/xajexatupe.cs
### Description:
When i took out or put in item to craft an item it crashed with crashlog provided above (Same happens for tool). There was lava inside and it was Blacksmith's Worktable.

**Comment by Vyraal1** [comment] 2018-02-03 22:19
This is most likely related to https://github.com/codetaylor/artisan-worktables/issues/47, as Kap and I were attempting similar things.

**Comment by codetaylor** [comment] 2018-02-03 22:21
Thank you for reporting this issue.

This is a duplicate of #47 and has been fixed in Athenaeum 1.12.2-1.6.4

**Closed as completed by codetaylor** 2018-02-03 22:21 UTC
Labels: duplicate

**Comment by codetaylor** [comment] 2018-02-03 22:22
https://minecraft.curseforge.com/projects/athenaeum/files/2527729

If you continue to experience this issue after updating the library, please contact me.
