### ISSUE TITLE
Crash with mod: Fancy Block Particles

### ISSUE THREAD

**Issue by BitBork** [codetaylor/artisan-worktables#8] opened 2018-01-04 17:32 UTC
Hi there Codetaylor

My client crashes whenever I try to place down any of the artisan's tables
Here's my crash log: 
https://gist.github.com/codetaylor/55cc350db2e37246af6fdf61fcfcf91b

**Comment by codetaylor** [comment] 2018-01-04 20:44
Looks like this is some kind of a mod interaction problem with Fancy Block Particles.

```
...
at com.TominoCZ.FBP.block.FBPAnimationDummyBlock.getSoundType(FBPAnimationDummyBlock.java:291)
...
```

Thanks for the report.

**Comment by codetaylor** [comment] 2018-01-04 21:31
Confirmed with latest version of Artisan Worktables, Athenaeum, and Fancy Block Particles.

https://gist.github.com/codetaylor/d0519917a474c9166f0aa9579309e283

**Comment by codetaylor** [comment] 2018-01-04 22:54
I know it's not ideal, but a temporary solution to this problem is to navigate to `config/FBP/Particle.properties` and disable the fancy place animation like so:

```
fancyPlaceAnim=false
```

Another solution is to blacklist the fancy placement animations for my worktables using the file:

```
config/FBP/AnimBlockExceptions.txt
```

**Comment by BitBork** [comment] 2018-01-05 13:15
Thanks for the fix Codetaylor

I disabled the worktables to be blacklisted in the fancyanimations, works perfectly.

**Comment by BitBork** [comment] 2018-01-05 13:16
Thanks for the fix Codetaylor

I disabled the worktables by blacklisting them in the fancyanimations config, works perfectly.
(Also unrelated question: are the worktables ctgui compatible? Can't seem to bring up the interface.)

**Comment by codetaylor** [comment] 2018-01-05 17:00
AFAIK, they are not CTGUI compatible. I did not add anything to specifically support that.

Also, I contacted the author of FBP [here](https://github.com/TominoCZ/FancyBlockParticles/issues/39) and they said that this issue is a known issue and will be fixed in the next release (of FBP). I plan to leave this issue open until it is verified fixed in case others have the same problem.

**Closed as completed** 2019-10-16 19:00 UTC
Labels: reproduced, mod interaction
